### ISSUE TITLE
Assessment form resets on refocus

### ISSUE THREAD

**Issue by FjodorvRijsselberg** [FC4E-CAT/fc4e-cat-ui#132]
**Describe the bug**
The issue occurs when filling out an assessment on the third step in /assessments/create. When filling out the assessment form, the form answers get wiped on refocus of the page. This means that if you click to another window and click back to the form, the state will reset and clear out any filled in form answers.

**To Reproduce**
1. Create a validation request for Bob or Alice.
2. Approve it as an admin.
3. Create an assessment as Bob or Alice.
4. Complete step 1 and 2.
5. Partially fill out the form in step 3.
6. Click outside of the browser context.
7. Click back on the form.

**Expected behavior**
The state should not get wiped on refocus.

**Desktop:**
 - OS: Ventura 13.6.1 (22G313)
 - Browser: Brave 1.16.114
 - Version: latest devel branch for both UI and API.

**Additional context**
If this is already known/in the backlog please feel free to close the ticket.

**Comment by themiszamani** [comment]
@FjodorvRijsselberg could you please check again now before we close it?
Best
Themis

**Comment by FjodorvRijsselberg** [comment]
I've checked it and everything is working nicely.
