### ISSUE TITLE
Admin dropdown disappears on smaller window

### ISSUE THREAD

**Issue by FjodorvRijsselberg** [FC4E-CAT/fc4e-cat-ui#138]
**Describe the bug**
The issue occurs when resizing the window when logged in as the admin. If the window is made too small the admin dropdown button wil disappear.

**To Reproduce**
1. Login as admin.
2. Make the width of the window smaller.
3. The admin dropdown button disappears.

**Expected behavior**
The admin dropdown button should not disappear.

**Desktop**
 - OS: Ventura 13.6.1 (22G313)
 - Browser: Brave 1.16.114
 - Version: latest devel branch for both UI and API.
 
**Screenshot of missing button**
![Screenshot 2024-02-02 at 09 23 25](https://github.com/FC4E-CAT/fc4e-cat-ui/assets/97509197/e844fadf-adb9-470f-9c7f-ae9227e1223a)

**Additional context**
This is a small issue and should only bother people on tablets or phones.

**Comment by themiszamani** [comment]
Hi @FjodorvRijsselberg 
In bootstrap when the window is small, all the menus are under the burger menu. So the admin options are actually there see in the attached photo. 

<img width="148" alt="Screenshot 2024-02-05 at 2 32 13 PM" src="https://github.com/FC4E-CAT/fc4e-cat-ui/assets/1556231/d2450976-65d0-4136-a5a2-0fcbd49a8c91">

We can discuss for a new position of the admin menu if you want.
