### ISSUE TITLE
Issue validation request form

### ISSUE THREAD

**Issue by FjodorvRijsselberg** [FC4E-CAT/fc4e-cat-ui#139]
**Describe the bug**
The issue occurs when filling out the form on the /validations/request page. if the Organization Name field and the Organization Role field have been filled out and you submit, the page return the user to the the /validations page and throws this error:
_Error during validation request submission._ The Actor field is left empty, but the page does not let the user know that this field is missing. Instead it redirects the user and throws an error. 

Small extra issue: When the Organization Name field is not filled out, only the Organization Website gets highlighted in red.

**To Reproduce**
1. Login as any user.
2. Update the profile information.
3. Create a new validation.
4. Fill out the Organization Name and the Organization Role.
5. Click the submit button.
6. User will be redirected to the /validations page and an error will be thrown.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
- OS: Ventura 13.6.1 (22G313)
- Browser: Brave 1.16.114
- Version: latest devel branch for both UI and API.

**Comment by themiszamani** [comment]
@FjodorvRijsselberg could you please check it? It is solved now. If you are ok we can close it. 
Best
Themis

**Comment by FjodorvRijsselberg** [comment]
This is working now, looks great!
