### ISSUE TITLE
Assessment creation page form error

### ISSUE THREAD

**Issue by FjodorvRijsselberg** [FC4E-CAT/fc4e-cat-ui#140]
**Is your feature request related to a problem? Please describe.**
This issue occurs when filling out the form to create an assessment on step 2 of the assessments/create page. If the Name field in the General Info accordion or the Subject fields in the Subject of assessment accordion are not filled out, the page throws an error when clicking the Create button. This error only states _Error during assessment creation_.  

**Describe the solution you'd like**
Show which fields specifically require to be filled out to be able to create the assessment. This can be done by highlighting them in red and adding text. (As is done on the other forms in the application). I can imagine this solution is hard to implement, because the user can click the Create button while the context is on a different step than Step 2.

**Describe alternatives you've considered**
An alternative would be to change the error text in the alert. For example if the Name field in the General Info accordion is missing it could throw an alert with the text "A unique name for the assessment is required".

**Comment by themiszamani** [comment]
@FjodorvRijsselberg this is done
