### ISSUE TITLE
Public assessment issue

### ISSUE THREAD

**Issue by FjodorvRijsselberg** [FC4E-CAT/fc4e-cat-ui#151]
**Describe the bug**
Currently the only required fields for creating an assessment are the general, subject, and license information. These are filled out in step 2 of the assessment creation process. This means it is currently possible to create an assessment that has no filled out fields in step 3. For an assessment with a private license this is not an issue, since it can be edited or deleted after the fact. 

In the case of a public assessment this causes an issue. It is currently impossible to delete or edit public assessments. This means if someone accidentally creates an empty public assessment it cannot be deleted or edited. 

**To Reproduce**
1. Login as a validated user.
2. Go to '/assessments/create'.
3. Select a role in step 1.
4. Filled out step 2 and specify the license as public.
5. Press the 'Create' button.
6. Check that the assessment is empty cannot be deleted or edited.

**Expected behavior**
Two options could be looked into here. Either some of the fields in the third step should be required (this can be depended on the license). Or a user (potentially an admin) can remove the public assessment.

**Desktop (please complete the following information):**
- OS: Ventura 13.6.1 (22G313)
- Browser: Brave 1.16.114
- Version: latest devel branch for both UI and API.

**Comment by themiszamani** [comment]
Dear @FjodorvRijsselberg 
Public Assessments will be published to Zenodo. 
By default we have a rule that you cannot delete a public assessment.
