### ISSUE TITLE
Maximum field length (50) on Subject of Assessment (sub)form.

### ISSUE THREAD

**Issue by wilkos-dans** [FC4E-CAT/fc4e-cat-ui#187]
**Describe the bug**
When editing (and probably also creating) the subject of an assessment in the UI, the fields 'Subject ID', 'Subject Name' and 'Subject Type', which are all mandatory fields raise an error on submitting the form, if one or more of the them contains a string with more than 50 characters.
A red alert/dialog box complaining about the database instantly pops up and disappears again. I think a max length should be applied to these three form fields, since the database fields (table Subject) are a varchar(50).

**Screenshots**
![image001](https://github.com/FC4E-CAT/fc4e-cat-ui/assets/13217223/6b41385a-8d7c-408b-bbd5-9cd5205786be)

**Comment by themiszamani** [comment]
Thank you @wilkos-dans 
we will ping you when it is ready

**Comment by themiszamani** [comment]
done on
